### ISSUE TITLE
Calendar empty

### ISSUE THREAD

**Issue by msemtd** [NottingHack/website#27]
The calendar on the website has no content (http://nottinghack.org.uk/?page_id=309) whereas the google calendar has loads of items (https://www.google.com/calendar/ical/info%40nottinghack.org.uk/public/basic.ics) - are the two supposed to be linked?

**Comment by jangojarango** [comment]
Hi,

I've had a quick look into the google calendar plugins, and from what I could see, the calendar plugin tries to grab content from ( http://www.google.com/calendar/feeds/info%40nottinghack.org.uk/private-acbf60a032394b53e3caae31e5c725eb/ ). This, when called from the browser, returns a "403 forbidden" - which, to me, would suggest that this is simply an old link?

could anyone with the dev environment set up have a go at trying to renew this, or am I wrong?

**Comment by geeksareforlife** [comment]
This is not surprising, as this was thrown together by me in a short space
of time.

There isn't a dev environment for this, it should just work on a wordpress
install, but I haven't looked at it in a long time.

Happy for anyone to look at it, if not, I will try to soon.

J

**Comment by dpslwk** [comment]
I guessing either the key is out of date or worse google changed there API

If you can figure out new URL that work a give a pul request we can include it, 
Im sort on time to look into this myself.


'RepRap' Matt

**Comment by jangojarango** [comment]
Will do once I'm in le space! 
(written on a mobile device - typos included) 
On 7 Apr 2015 5:28 pm, "dps.lwk" <notifications@github.com> wrote:I guessing either the key is out of date or worse google changed there API

If you can figure out new URL that work a give a pul request we can include it, 
Im sort on time to look into this myself.


'RepRap' Matt

**Comment by dpslwk** [comment]
The URL change by @jangojarango but did not fix it.
pretty sure google changed the API and so I suspect both scripts might need a bigger rewrite.

**Comment by jangojarango** [comment]
seems one issue with my initially attempted fix was that I did replace the url, but with an https prefix which might confuse php - however, I have also found that for some reason there is a "full" parameter added to the fully assembled URL that is being retrieved from Gcal - I don't know what this parameter does, but when it's not there it works when i fetch the full url manually :)

I have updated both of this in my current pull request (#31)

it does seem like a google calendar REST-API update is the culprit - I hope that the returned xml didn't change much though (and judging from the api reference docs, and "what's new in google calendar api v3" it shouldn't be the case...)

let's see whether this works...

**Comment by geeksareforlife** [comment]
This has been fixed by fully replacing calendar
